env:
  browser: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  space-before-function-paren:
    - error
    - named: never
plugins:
  - html
ignorePatterns:
  - 'tmp/'
  - 'node_modules/'
