name: Go
on: [push]
jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: setup
      run: curl -L https://git.io/fjaxx | repo=ysmood/kit bin=godev sh
 
    - name: test
      run: godev -l -m 90

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  others:

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: test
      run: go test
