name: Test
on:
  push:
    branches:
      - '**'

  pull_request:

  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - run: go generate

      - run: go test -cover -coverprofile=coverage.txt ./...

      - run: go run ./lib/utils/check-cov

      - uses: codecov/codecov-action@v1
        if: ${{ always() }}

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - name: test
        run: go test -race -run /

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - name: test
        run: go test -race -run /

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          docker build -t rodorg/rod -f lib/docker/Dockerfile .
          docker build -t test -f lib/docker/test.Dockerfile .
          docker run -v $(pwd):/t -w /t test

      - uses: actions/upload-artifact@v2
        with:
          name: review-fonts
          path: tmp/fonts.pdf
