name: Test Mac
on:
  push:
    branches:
      - '**'

  pull_request:

jobs:
  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - run: go test -race -timeout-each=20m

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cdp-log-macos
          path: tmp/cdp-log
